name: Bicep Build Test

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.bicep"

jobs:
  get_changed_files:
    name: Test Bicep Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Bicep Build to Test
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter '*.bicep' | ForEach-Object {$_.FullName} | bicep build 
          
